### ISSUE TITLE
Primus and omega supreme

### ISSUE THREAD

**Issue by dalemeonsah** [primus/omega-supreme#9]
Trying primus 3.2.0 and omega supreme 2.0.0

I get error when I try 

`primus.use('omega-supreme', require('omega-supreme'))`

Error:
chat-api/node_modules/primus/index.js:689
    throw new PrimusError('The plugin name was already defined', this);
    ^
PrimusError: The plugin name was already defined

then I try it as a plugin:

`primus.plugin('omega-supreme', require('omega-supreme))`

Another error comes up:
/chat-api/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^
TypeError: primus.forward is not a function

It seems primus does not have forward method from the omega-supreme plugin.
Could you please help me?
Thanks

**Comment by 3rd-Eden** [comment]
Your primus version is really old, I would suggest updating to latest primus and then use the `primus.plugin` method to add this plugin.

**Comment by dalemeonsah** [comment]
I use primus.io and it is the latest version 3.2.0

**Comment by dalemeonsah** [comment]
any tweaks if I use primus.io ?

**Comment by lpinca** [comment]
@dalemeonsah if you use https://github.com/cayasso/primus.io the easiest way for you right now is to use `omega-supreme@1.0.0` and load the plugin with the `primus.use` method.
The only difference between `omega-supreme@1.0.0` and `omega-supreme@2.0.0` is that the latter works with `primus@6.0.0`.
